result component for 3d mesh
jina-ai/jina-ui pull request #37
Opened 2021-09-10 13:19 UTC by Roshanjossey

2021-09-13 09:27 UTC, BastinJafari approved these changes

2021-09-13 12:17 UTC, BastinJafari approved these changes

2021-09-15 11:52 UTC, imsergiy approved these changes

2021-09-20 08:56 UTC, BastinJafari requested changes

2021-09-20 08:56 UTC, BastinJafari commented on packages/jinajs/src/jinaClient.ts
> +      //   `Could not reach flow at ${this.baseURL}. Check the URL and make sure CORS is enabled.`
Forgot to delete?

2021-09-22 07:15 UTC, merged